[package]
name = "poise_paginator"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = "1.45.0"
poise = { workspace = true }

[workspace.dependencies]
poise = "0.6.1"

[workspace]
members = ["examples/*"]
